### ISSUE TITLE
Two oddities

### ISSUE THREAD

**Issue by KateFreier** [jnolis/banned-license-plates#1] opened 2019-06-07 23:27 UTC
First off, thank you so much for sharing this.  I saw your talk at SDSS and am totally inspired by this project of yours.  Two issues I've found running your code (with the model you built):

1. When I have max_length=6, an error pops up that seems to be based on having a max_length of 7 hard-coded somewhere.  This is the error message: 
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  ValueError: Error when checking input: expected input_1 to have shape (7, 39) but got array with shape (6, 39)

2.  Running the generate_result function with max_length=7 and temperature=3, I got "GS7RSHLWX", a 9 character result.  Any ideas what happened there?

Thanks!

**Comment by jnolis** [comment] 2019-06-09 03:16
I'm glad you liked the talk! And the repo! Let me address your comments:

1. I just tried changing the max_length to 5 and it worked for me. I suspect the issue is that you changed the max_length parameter without retraining the model. I didn't put in the documentation that if you change anything in the parameters file you need to retrain the model so I'll add that.
2. Yup! This is actually a spillover from the [pet names project](https://github.com/nolis-llc/pet-names) where having a result longer than the max is fine. I just changed the code so the max length is enforced (which is more intuitive)

The code has been pushed to the repo. Let me know if this fixes your issue (or doesn't!) If it looks good I'll close it.

**Closed as completed** 2019-06-15 22:39 UTC
